global:
  scrape_interval: 1s
  evaluation_interval: 1s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'networktraffic'
    static_configs:
      - targets: ['localhost:59121']
    metrics_path: '/metrics'
    scrape_interval: 1s

  - job_name: 'packetloss'
    static_configs:
      - targets: ['localhost:59122']
    metrics_path: '/metrics'
    scrape_interval: 1s
  