# Basic settings
interface=$LAN_INTERFACE
bind-interfaces
domain-needed
bogus-priv

# DNS settings (Cloudflare)
server=1.1.1.1

# IPv4 DHCP settings
dhcp-range=$DHCP_IPV4_START,$DHCP_IPV4_END,255.255.255.0,24h
dhcp-option=option:router,${LAN_IPV4_GATEWAY%/*}
dhcp-option=option:dns-server,${LAN_IPV4_GATEWAY%/*}

# Log settings
log-dhcp
# Cache size
cache-size=500
